<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class KindergartenAssesmentRecordDetail  extends Model
{

    protected $fillable = [
        'introduce_name',
        'greet_teacher',
        'answer_question',
        'ask_question',
        'involve_in_conversation',
        'state_willingness',
        'pronounce_word',
        'inform_calendar',
        'sing_songs',
        'recite_rhymes',
        'listen_to_teacher',
        'listen_to_classmates',
        'follow_instruction',
        'respond_to_questions',
        'respect_teachers',
        'respect_friends',
        'speak_politely_to_others',
        'care_to_others',
        'share_with_others',
        'help_others',
        'obey_teachers',
        'get_along_with_classmates',
        'give_attention_to_the_lesson',
        'do_given_task_independently',
        'finish_task_as_order',
        'willing_to_perform',
        'willing_to_take_turn',
        'dress_neatly',
        'neaten_belonging',
        'take_care_of_school_property',
        'keep_clean',
        'enjoy_doing_art_works',
        'able_to_eat_using_utensils',
        'color_picture_in_designated_area',
        'use_paint_brush',
        'paste_paper',
        'draw_shape',
        'fold_paper',
        'cut_paper_using_scissors',
        'able_to_catch',
        'able_to_throw',
        'able_to_hop',
        'able_to_walk_with_bean_bag',
        'able_to_balance_while_running',
        'able_to_balance_on_plank',
        'able_to_follow_movements',
        'participate_in_games',

        'trace_alphabets',
        'copy_alphabets',
        'copy_words',
        'recognize_sound_of_the_alphabets',
        'recognize_shapes_of_the_alphabets',
        'identify_first_sound_of_3_letters_word',
        'identify_second_sound_of_3_letters_word',
        'identify_third_sound_of_3_letters_word',
        'build_3_letters_word',
        'read_3_letters_word',
        'read_3_letters_word_phrase',
        'read_3_letters_word_sentence',

        'identify_shapes',
        'master_quantity_0_10',
        'recognize_shapes_of_the_numbers',
        'sequence_numbers',
        'compare_small_sizes',
        'compare_big_sizes',
        'discriminate_more_and_less',
        'understand_ones_and_ten',
        'able_to_add_objects',
        'compare_long_lenght',
        'compare_short_length',
        'understand_tens',
        'recognize_time',

        'mandarin_reading',
        'mandarin_writing',
        'mandarin_listening',
        'mandarin_speaking',
        'mandarin_test',

        'additional_program_1',
        'additional_program_1_score',
        'additional_program_2',
        'additional_program_2_score',
        'additional_program_3',
        'additional_program_3_score',

        'write_3_letters',
        'write_blend_consonant',
        'build_3_letters',
        'read_3_letters',
        'build_3_letters_word_phrase',
        'build_3_letters_word_sentence',
        'identify_blend_consonant',
        'build_blend_consonant',
        'read_blend_consonant_word',
        'read_blend_consonant_phrase',
        'read_blend_consonant_sentence',

        'understand_hundreds',
        'able_to_subtract_numbers',
        'able_to_subtract_objects',
        'understand_units_and_tens',
        'able_to_add_numbers',
        'recognize_time_half_past',
        'understand_odd_and_even_numbers',
        'compare_tall_height',
        'compare_short_height',

        'indo_writing_properly_in_the_line',
        'indo_recognizing_letters',
        'indo_recognizing_syllables',
        'indo_reading_words',
        'indo_reading_phrase',
        'indo_reading_sentence',
        'indo_reading_comprehension_story',

        'hold_pencil_appropriately',
        'stroke_pencil',
        'color_picture',
        'recognize_shape_of_i_l_t_f_k',
        'recognize_shape_of_r_n_m_c_a_d_g',
        'use_of_glue',
        'trace_alphabets_of_i_l_t_f_k',
        'recognize_sound_of_r_n_m_c_a_d_g',
        'recognize_sound_of_i_l_t_f_k',

        'able_to_jump',
        'trace_vertical_lines',
        'trace_horizontal_lines',
        'trace_diagonal_lines',
        'trace_curve_lines',
        'trace_shapes',
        'trace_alphabets_r_n_m_c_a_d_g',

        'recognize_sound_of_h_b_p_e_o_q_s',
        'recognize_shape_of_h_b_p_e_o_q_s',
        'trace_alphabets_h_b_p_e_o_q_s',

        'recognize_sound_of_u_y_j_v_w_x_z',
        'recognize_shape_of_u_y_j_v_w_x_z',
        'trace_alphabets_u_y_j_v_w_x_z',

        'identify_colors_red_blue_yellow',
        'recognize_colors_green_orange_purple',
        'identify_number_0_5',
        'understand_quantity_0_5',
        'identify_shapes_square_circle_triangle',
        'discriminate_long_and_short',
        'identify_number_6_9',
        'understand_quantity_6_9',
        'recognize_shapes_rectangle_diamond_oval',
        'identify_number_10_12',
        'understand_quantity_10_12',
        'recognize_colors_black_white_brown_pink',
        'identify_number_13_15',
        'understand_quantity_13_15',

        'report_word',
        'repeat_day_date_month_year',
        'mention_day_date_month_year',
        'inform_age',
        'inform_gender',
        'name_body_parts',
        'do_given_task_independetly',
        'recognize_sound_of_i_l_t',
        'sing_song',
        'able_to_eat_independetly',
        'able_to_match_object',
        'recognize_colors_red_yellow_blue',

        'audio_reading',
        'spelling',
        'computer',
        'science',
    ];

}
